# Generated by Django 4.1.4 on 2022-12-10 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(help_text='user_name', max_length=50)),
                ('user_email', models.CharField(help_text='user_email', max_length=50)),
                ('user_password', models.CharField(help_text='user_password', max_length=8)),
                ('user_phone', models.IntegerField(help_text='user_phone', max_length=10)),
                ('user_city', models.CharField(help_text='user_city', max_length=30)),
                ('user_pic', models.ImageField(upload_to='uploads/')),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
