# Generated by Django 4.1.4 on 2022-12-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_usermodel_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_phone',
            field=models.IntegerField(default=None, help_text='user_phone'),
        ),
    ]
