# Generated by Django 4.1.4 on 2022-12-10 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_usermodel_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_phone',
            field=models.CharField(help_text='user_phone', max_length=10),
        ),
    ]
