# Generated by Django 4.1.4 on 2022-12-10 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_complaintmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaintmodel',
            old_name='Approx_date_time',
            new_name='Approx_date',
        ),
    ]
