# Generated by Django 4.1.4 on 2022-12-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_complaintmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintmodel',
            name='status',
            field=models.CharField(default='Pending', help_text='status', max_length=20),
        ),
    ]
