# Generated by Django 4.1.4 on 2022-12-12 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0010_feedbackmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackmodel',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userapp.usermodel'),
        ),
    ]
