# Generated by Django 4.1.4 on 2022-12-13 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_alter_complaintmodel_suspect_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_key',
            field=models.CharField(help_text='user_key', max_length=18, null=True),
        ),
    ]
