# Generated by Django 4.1.4 on 2022-12-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_usermodel_user_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_key',
            field=models.CharField(help_text='user_key', max_length=500, null=True),
        ),
    ]
