# Generated by Django 4.1.4 on 2022-12-13 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_alter_usermodel_user_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='user_city',
            field=models.CharField(help_text='user_city', max_length=300),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_email',
            field=models.CharField(help_text='user_email', max_length=500),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_name',
            field=models.CharField(help_text='user_name', max_length=500),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_password',
            field=models.CharField(help_text='user_password', max_length=800),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_phone',
            field=models.CharField(help_text='user_phone', max_length=100),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='user_pic',
            field=models.ImageField(max_length=300, upload_to='uploads/'),
        ),
    ]
