# Generated by Django 4.1.4 on 2022-12-13 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0015_alter_usermodel_user_city_alter_usermodel_user_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='user_key',
        ),
    ]
