# Generated by Django 4.1.4 on 2022-12-13 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0016_remove_usermodel_user_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaintmodel',
            name='Evidence',
        ),
    ]
