# Generated by Django 4.1.4 on 2022-12-13 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0017_remove_complaintmodel_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermodel',
            name='user_key',
            field=models.CharField(help_text='user_key', max_length=500, null=True),
        ),
    ]
