# Generated by Django 4.0.5 on 2022-12-17 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0022_complaintmodel_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintmodel',
            name='Evidence_block_chain',
            field=models.CharField(help_text='Evidence_block_chain', max_length=500, null=True),
        ),
    ]
