# Generated by Django 4.0.5 on 2022-12-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0023_complaintmodel_evidence_block_chain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintmodel',
            name='Evidence',
            field=models.FileField(default=None, max_length=500, upload_to='uploads/'),
        ),
    ]
