# Generated by Django 4.0.5 on 2022-12-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0024_alter_complaintmodel_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintmodel',
            name='case_fill_as',
            field=models.CharField(default=None, help_text='case_fill_as', max_length=50, null=True),
        ),
    ]
