# Generated by Django 4.0.5 on 2022-12-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0025_complaintmodel_case_fill_as'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaintmodel',
            old_name='case_fill_as',
            new_name='Case_fill_as',
        ),
        migrations.AddField(
            model_name='complaintmodel',
            name='Disard_reason',
            field=models.CharField(default=None, help_text='Disard_reason', max_length=500, null=True),
        ),
    ]
