# Generated by Django 4.0.5 on 2022-12-17 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0026_rename_case_fill_as_complaintmodel_case_fill_as_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='complaintmodel',
            old_name='Disard_reason',
            new_name='Discard_reason',
        ),
    ]
