# Generated by Django 4.0.5 on 2022-12-17 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0027_rename_disard_reason_complaintmodel_discard_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintmodel',
            name='status',
            field=models.CharField(default='Received', help_text='status', max_length=20),
        ),
    ]
